### ISSUE TITLE
Repository clevrer_dynamic_propnet not available

### ISSUE THREAD

**Issue by gabrielsluz** [zfchenUnique/DCL-Release#1]
Hello,
I tried to run the code but I couldn't because the following command does not work:

`git clone https://github.com/zfchenUnique/clevrer_dynamic_propnet.git`

Is the repository `clevrer_dynamic_propnet` available ?

Thank you in advance.

**Comment by zfchenUnique** [comment]
Dear gabrielsluz,

         Thanks for your reminder!
         I forget to change the access for the repo and will work soon.

Sincerely,
Zhenfang
