### ISSUE TITLE
No such file or directory: '../clevrer/tubeProposalsGt'

### ISSUE THREAD

**Issue by z-yf17** [zfchenUnique/DCL-Release#4]
Hello. Thank you for sharing code!

I have some trouble when I do the step-by-step training at step1.

I have already organized the data as shown in the instruction. When I run 'sh scripts/script_gen_tubes.sh', here comes an error:

`Traceback (most recent call last): File "scripts/script_gen_tube_proposals.py", line 1923, in <module>
    compute_recall_and_precision(opt)
  File "scripts/script_gen_tube_proposals.py", line 786, in compute_recall_and_precision
    pk_fn_list = get_sub_file_list(out_gt_path, 'pk')
  File "scripts/script_gen_tube_proposals.py", line 585, in get_sub_file_list
    for file_name in os.listdir(folder_name):
FileNotFoundError: [Errno 2] No such file or directory: '../clevrer/tubeProposalsGt'`

It seems that there is no folder called 'tubeProposalsGt'. 

I would appreciate it if you can tell me what I should do to fix it.

Thanks a lot!

**Comment by zfchenUnique** [comment]
Hi, thanks for your interest in the code.
The tubProposalGt is something that I previously manually generate to estimate the quality of the generated tubes. There is no need to use it to run the model. To generate tubeProposalsGt, you need to download the original image proposals from mask-RCNN and align them across frames based on the attribute prediction.
Regards,
Zhenfang

**Comment by z-yf17** [comment]
> 

Thanks for your reply!

I skipped the function 'compute_recall_and_precision' and succcessfully extracted object trajectories for train and val set. 

I met a new problem when I move on to step2. Error occurs when loading questions:

`Traceback (most recent call last):
  File "scripts/trainval_tube_v2.py", line 356, in <module>
    main()
  File "scripts/trainval_tube_v2.py", line 95, in main
    validation_dataset = build_clevrer_dataset(args, 'validation')
  File "/home/zhangyifan/DCL-Release/clevrer/dataset_clevrer.py", line 1373, in build_clevrer_dataset
    dataset = clevrerDataset(args, phase=phase, img_transform=image_transform)
  File "/home/zhangyifan/DCL-Release/clevrer/dataset_clevrer.py", line 156, in __init__
    self._init_correct_question(phase)
  File "/home/zhangyifan/DCL-Release/clevrer/dataset_clevrer.py", line 232, in _init_correct_question
    oe_ques_info_dict = jsonload(oe_ques_full_path)
  File "/home/zhangyifan/DCL-Release/clevrer/utils.py", line 3207, in jsonload
    f = open(path)
FileNotFoundError: [Errno 2] No such file or directory: '../language_parsing/data/new_results/oe_1000pg_val_new.json'`

I can't find the folder named 'language_parsing' and It seems not generated automatically. The data is organized as shown in the instruction, but I'm wondering whether it is sufficient for the next steps. Could you please tell me what else I should do to make through the step-by-step training process?

I'm looking forward to your reply!

Thanks.

**Comment by zfchenUnique** [comment]
Hi, it seems that you need the parsed programs from https://drive.google.com/drive/folders/1dydkLN1A9GWTaMK8QaxpWs6Pt4Eszsaw as described in the Readme.md .
You should be able to comparable or slighly-better performance reported in the ICLR paper.
Thanks again for your interest and good luck!
Regards,
Zhenfang
